import { getWebhookRequest } from "./discord";
import { mergeRequests } from "./merge";
import { GithubEvent } from "./github";
import { checkRunScenarios, pushScenarios } from "./scenarios";

export const a = {
  type: "deployment_status.created",
  deployment_status: {
    url: "https://api.github.com/repos/flirtual/flirtual/deployments/5937805797/statuses/16895408778",
    id: 16895408778,
    node_id: "DES_kwDOJp7HD88AAAAD7wt6ig",
    state: "success",
    creator: {
      login: "ariesclark",
      id: 10256477,
      node_id: "MDQ6VXNlcjEwMjU2NDc3",
      avatar_url: "https://avatars.githubusercontent.com/u/10256477?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ariesclark",
      html_url: "https://github.com/ariesclark",
      followers_url: "https://api.github.com/users/ariesclark/followers",
      following_url: "https://api.github.com/users/ariesclark/following{/other_user}",
      gists_url: "https://api.github.com/users/ariesclark/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ariesclark/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ariesclark/subscriptions",
      organizations_url: "https://api.github.com/users/ariesclark/orgs",
      repos_url: "https://api.github.com/users/ariesclark/repos",
      events_url: "https://api.github.com/users/ariesclark/events{/privacy}",
      received_events_url: "https://api.github.com/users/ariesclark/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    description: "",
    environment: "canary",
    target_url: "https://github.com/flirtual/flirtual/actions/runs/31987109115/job/95263908430",
    created_at: "2026-08-17T02:11:06Z",
    updated_at: "2026-08-17T02:11:06Z",
    deployment_url: "https://api.github.com/repos/flirtual/flirtual/deployments/5937805797",
    repository_url: "https://api.github.com/repos/flirtual/flirtual",
    environment_url: "https://c4bef7b.flirtual.dev",
    log_url: "https://github.com/flirtual/flirtual/actions/runs/31987109115/job/95263908430",
    performed_via_github_app: null,
  },
  deployment: {
    url: "https://api.github.com/repos/flirtual/flirtual/deployments/5937805797",
    id: 5937805797,
    node_id: "DE_kwDOJp7HD88AAAABYeu55Q",
    task: "deploy",
    original_environment: "canary",
    environment: "canary",
    description: null,
    created_at: "2026-08-17T02:09:15Z",
    updated_at: "2026-08-17T02:11:06Z",
    statuses_url: "https://api.github.com/repos/flirtual/flirtual/deployments/5937805797/statuses",
    repository_url: "https://api.github.com/repos/flirtual/flirtual",
    creator: {
      login: "ariesclark",
      id: 10256477,
      node_id: "MDQ6VXNlcjEwMjU2NDc3",
      avatar_url: "https://avatars.githubusercontent.com/u/10256477?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ariesclark",
      html_url: "https://github.com/ariesclark",
      followers_url: "https://api.github.com/users/ariesclark/followers",
      following_url: "https://api.github.com/users/ariesclark/following{/other_user}",
      gists_url: "https://api.github.com/users/ariesclark/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ariesclark/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ariesclark/subscriptions",
      organizations_url: "https://api.github.com/users/ariesclark/orgs",
      repos_url: "https://api.github.com/users/ariesclark/repos",
      events_url: "https://api.github.com/users/ariesclark/events{/privacy}",
      received_events_url: "https://api.github.com/users/ariesclark/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    sha: "c4bef7bffe39cd4f08dab6566f0099555dbe7019",
    ref: "main",
    payload: {},
    transient_environment: false,
    production_environment: false,
    performed_via_github_app: {
      id: 15368,
      client_id: "Iv1.05c79e9ad1f6bdfa",
      slug: "github-actions",
      node_id: "MDM6QXBwMTUzNjg=",
      owner: {
        login: "github",
        id: 9919,
        node_id: "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
        avatar_url: "https://avatars.githubusercontent.com/u/9919?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/github",
        html_url: "https://github.com/github",
        followers_url: "https://api.github.com/users/github/followers",
        following_url: "https://api.github.com/users/github/following{/other_user}",
        gists_url: "https://api.github.com/users/github/gists{/gist_id}",
        starred_url: "https://api.github.com/users/github/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/github/subscriptions",
        organizations_url: "https://api.github.com/users/github/orgs",
        repos_url: "https://api.github.com/users/github/repos",
        events_url: "https://api.github.com/users/github/events{/privacy}",
        received_events_url: "https://api.github.com/users/github/received_events",
        type: "Organization",
        user_view_type: "public",
        site_admin: false,
      },
      name: "GitHub Actions",
      description: "Automate your workflow from idea to production",
      external_url: "https://help.github.com/en/actions",
      html_url: "https://github.com/apps/github-actions",
      created_at: "2018-07-30T09:30:17Z",
      updated_at: "2026-06-18T16:17:48Z",
      permissions: {
        actions: "write",
        administration: "read",
        artifact_metadata: "write",
        attestations: "write",
        checks: "write",
        code_quality: "write",
        contents: "write",
        copilot_requests: "write",
        deployments: "write",
        discussions: "write",
        drives: "write",
        issues: "write",
        merge_queues: "write",
        metadata: "read",
        models: "read",
        packages: "write",
        pages: "write",
        pull_requests: "write",
        repository_hooks: "write",
        repository_projects: "write",
        security_events: "write",
        statuses: "write",
        vulnerability_alerts: "read",
      },
      events: [
        "branch_protection_rule",
        "check_run",
        "check_suite",
        "create",
        "delete",
        "deployment",
        "deployment_status",
        "discussion",
        "discussion_comment",
        "fork",
        "gollum",
        "issues",
        "issue_comment",
        "label",
        "merge_group",
        "milestone",
        "page_build",
        "public",
        "pull_request",
        "pull_request_review",
        "pull_request_review_comment",
        "push",
        "registry_package",
        "release",
        "repository",
        "repository_dispatch",
        "status",
        "watch",
        "workflow_dispatch",
        "workflow_run",
      ],
    },
  },
  check_run: {
    id: 95263908430,
    name: "release (canary)",
    node_id: "CR_kwDOJp7HD88AAAAWLiviTg",
    head_sha: "c4bef7bffe39cd4f08dab6566f0099555dbe7019",
    external_id: "64845abc-ca52-502c-ad31-e2bb399bbbba",
    url: "https://api.github.com/repos/flirtual/flirtual/check-runs/95263908430",
    html_url: "https://github.com/flirtual/flirtual/actions/runs/31987109115/job/95263908430",
    details_url: "https://github.com/flirtual/flirtual/actions/runs/31987109115/job/95263908430",
    status: "completed",
    conclusion: "success",
    started_at: "2026-08-17T02:09:18Z",
    completed_at: "2026-08-17T02:11:05Z",
  },
  workflow: {
    id: 120172226,
    node_id: "W_kwDOJp7HD84HKa7C",
    name: ".github/workflows/frontend.yaml",
    path: ".github/workflows/frontend.yaml",
    state: "active",
    created_at: "2024-10-01T00:54:56.000Z",
    updated_at: "2024-11-26T21:50:14.000Z",
    url: "https://api.github.com/repos/flirtual/flirtual/actions/workflows/120172226",
    html_url: "https://github.com/flirtual/flirtual/blob/main/.github/workflows/frontend.yaml",
    badge_url:
      "https://github.com/flirtual/flirtual/workflows/.github/workflows/frontend.yaml/badge.svg",
  },
  workflow_run: {
    id: 31987109115,
    name: ".github/workflows/frontend.yaml",
    node_id: "WFR_kwLOJp7HD88AAAAHcpSM-w",
    head_branch: "main",
    head_sha: "c4bef7bffe39cd4f08dab6566f0099555dbe7019",
    path: ".github/workflows/frontend.yaml",
    // "display_title": "Revert \"Reapply \"test: bad commit\"\"",
    display_title: "fix(frontend): update dependency react-shepherd to v7",
    run_number: 1620,
    event: "push",
    status: "completed",
    conclusion: "success",
    workflow_id: 120172226,
    check_suite_id: 86723275012,
    check_suite_node_id: "CS_kwDOJp7HD88AAAAUMRwpBA",
    url: "https://api.github.com/repos/flirtual/flirtual/actions/runs/31987109115",
    html_url: "https://github.com/flirtual/flirtual/actions/runs/31987109115",
    pull_requests: [],
    created_at: "2026-08-17T02:09:14Z",
    updated_at: "2026-08-17T02:11:06Z",
    actor: {
      login: "ariesclark",
      id: 10256477,
      node_id: "MDQ6VXNlcjEwMjU2NDc3",
      avatar_url: "https://avatars.githubusercontent.com/u/10256477?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ariesclark",
      html_url: "https://github.com/ariesclark",
      followers_url: "https://api.github.com/users/ariesclark/followers",
      following_url: "https://api.github.com/users/ariesclark/following{/other_user}",
      gists_url: "https://api.github.com/users/ariesclark/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ariesclark/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ariesclark/subscriptions",
      organizations_url: "https://api.github.com/users/ariesclark/orgs",
      repos_url: "https://api.github.com/users/ariesclark/repos",
      events_url: "https://api.github.com/users/ariesclark/events{/privacy}",
      received_events_url: "https://api.github.com/users/ariesclark/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    run_attempt: 1,
    referenced_workflows: [],
    run_started_at: "2026-08-17T02:09:14Z",
    triggering_actor: {
      login: "ariesclark",
      id: 10256477,
      node_id: "MDQ6VXNlcjEwMjU2NDc3",
      avatar_url: "https://avatars.githubusercontent.com/u/10256477?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ariesclark",
      html_url: "https://github.com/ariesclark",
      followers_url: "https://api.github.com/users/ariesclark/followers",
      following_url: "https://api.github.com/users/ariesclark/following{/other_user}",
      gists_url: "https://api.github.com/users/ariesclark/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ariesclark/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ariesclark/subscriptions",
      organizations_url: "https://api.github.com/users/ariesclark/orgs",
      repos_url: "https://api.github.com/users/ariesclark/repos",
      events_url: "https://api.github.com/users/ariesclark/events{/privacy}",
      received_events_url: "https://api.github.com/users/ariesclark/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
  },
  action: "created",
  repository: {
    id: 647939855,
    node_id: "R_kgDOJp7HDw",
    name: "flirtual",
    full_name: "flirtual/flirtual",
    private: false,
    owner: {
      login: "flirtual",
      id: 80071112,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjgwMDcxMTEy",
      avatar_url: "https://avatars.githubusercontent.com/u/80071112?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/flirtual",
      html_url: "https://github.com/flirtual",
      followers_url: "https://api.github.com/users/flirtual/followers",
      following_url: "https://api.github.com/users/flirtual/following{/other_user}",
      gists_url: "https://api.github.com/users/flirtual/gists{/gist_id}",
      starred_url: "https://api.github.com/users/flirtual/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/flirtual/subscriptions",
      organizations_url: "https://api.github.com/users/flirtual/orgs",
      repos_url: "https://api.github.com/users/flirtual/repos",
      events_url: "https://api.github.com/users/flirtual/events{/privacy}",
      received_events_url: "https://api.github.com/users/flirtual/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/flirtual/flirtual",
    description: "The first VR dating app",
    fork: false,
    url: "https://api.github.com/repos/flirtual/flirtual",
    forks_url: "https://api.github.com/repos/flirtual/flirtual/forks",
    keys_url: "https://api.github.com/repos/flirtual/flirtual/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/flirtual/flirtual/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/flirtual/flirtual/teams",
    hooks_url: "https://api.github.com/repos/flirtual/flirtual/hooks",
    issue_events_url: "https://api.github.com/repos/flirtual/flirtual/issues/events{/number}",
    events_url: "https://api.github.com/repos/flirtual/flirtual/events",
    assignees_url: "https://api.github.com/repos/flirtual/flirtual/assignees{/user}",
    branches_url: "https://api.github.com/repos/flirtual/flirtual/branches{/branch}",
    tags_url: "https://api.github.com/repos/flirtual/flirtual/tags",
    blobs_url: "https://api.github.com/repos/flirtual/flirtual/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/flirtual/flirtual/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/flirtual/flirtual/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/flirtual/flirtual/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/flirtual/flirtual/statuses/{sha}",
    languages_url: "https://api.github.com/repos/flirtual/flirtual/languages",
    stargazers_url: "https://api.github.com/repos/flirtual/flirtual/stargazers",
    contributors_url: "https://api.github.com/repos/flirtual/flirtual/contributors",
    subscribers_url: "https://api.github.com/repos/flirtual/flirtual/subscribers",
    subscription_url: "https://api.github.com/repos/flirtual/flirtual/subscription",
    commits_url: "https://api.github.com/repos/flirtual/flirtual/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/flirtual/flirtual/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/flirtual/flirtual/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/flirtual/flirtual/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/flirtual/flirtual/contents/{+path}",
    compare_url: "https://api.github.com/repos/flirtual/flirtual/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/flirtual/flirtual/merges",
    archive_url: "https://api.github.com/repos/flirtual/flirtual/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/flirtual/flirtual/downloads",
    issues_url: "https://api.github.com/repos/flirtual/flirtual/issues{/number}",
    pulls_url: "https://api.github.com/repos/flirtual/flirtual/pulls{/number}",
    milestones_url: "https://api.github.com/repos/flirtual/flirtual/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/flirtual/flirtual/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/flirtual/flirtual/labels{/name}",
    releases_url: "https://api.github.com/repos/flirtual/flirtual/releases{/id}",
    deployments_url: "https://api.github.com/repos/flirtual/flirtual/deployments",
    created_at: "2023-05-31T21:20:44Z",
    updated_at: "2026-08-17T02:09:25Z",
    pushed_at: "2026-08-17T02:09:12Z",
    git_url: "git://github.com/flirtual/flirtual.git",
    ssh_url: "git@github.com:flirtual/flirtual.git",
    clone_url: "https://github.com/flirtual/flirtual.git",
    svn_url: "https://github.com/flirtual/flirtual",
    homepage: "https://flirtual.com",
    size: 23422,
    stargazers_count: 35,
    watchers_count: 35,
    language: "TypeScript",
    has_issues: true,
    has_projects: true,
    has_downloads: false,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 6,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 43,
    license: {
      key: "agpl-3.0",
      name: "GNU Affero General Public License v3.0",
      spdx_id: "AGPL-3.0",
      url: "https://api.github.com/licenses/agpl-3.0",
      node_id: "MDc6TGljZW5zZTE=",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    has_pull_requests: true,
    pull_request_creation_policy: "all",
    topics: ["dating-app", "elixir", "phoenix", "typescript", "vr", "vrchat"],
    visibility: "public",
    forks: 6,
    open_issues: 43,
    watchers: 35,
    default_branch: "main",
    custom_properties: {
      Meow: "true",
    },
  },
  organization: {
    login: "flirtual",
    id: 80071112,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjgwMDcxMTEy",
    url: "https://api.github.com/orgs/flirtual",
    repos_url: "https://api.github.com/orgs/flirtual/repos",
    events_url: "https://api.github.com/orgs/flirtual/events",
    hooks_url: "https://api.github.com/orgs/flirtual/hooks",
    issues_url: "https://api.github.com/orgs/flirtual/issues",
    members_url: "https://api.github.com/orgs/flirtual/members{/member}",
    public_members_url: "https://api.github.com/orgs/flirtual/public_members{/member}",
    avatar_url: "https://avatars.githubusercontent.com/u/80071112?v=4",
    description: "The first VR dating app.",
  },
  sender: {
    login: "ariesclark",
    id: 10256477,
    node_id: "MDQ6VXNlcjEwMjU2NDc3",
    avatar_url: "https://avatars.githubusercontent.com/u/10256477?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ariesclark",
    html_url: "https://github.com/ariesclark",
    followers_url: "https://api.github.com/users/ariesclark/followers",
    following_url: "https://api.github.com/users/ariesclark/following{/other_user}",
    gists_url: "https://api.github.com/users/ariesclark/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ariesclark/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ariesclark/subscriptions",
    organizations_url: "https://api.github.com/users/ariesclark/orgs",
    repos_url: "https://api.github.com/users/ariesclark/repos",
    events_url: "https://api.github.com/users/ariesclark/events{/privacy}",
    received_events_url: "https://api.github.com/users/ariesclark/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
};

const b = {
  type: "push",
  ref: "refs/heads/renovate/tidewave-0.x",
  before: "6c7286bd6d3c62ed00622991183073a7cf44384f",
  after: "0000000000000000000000000000000000000000",
  repository: {
    id: 647939855,
    node_id: "R_kgDOJp7HDw",
    name: "flirtual",
    full_name: "flirtual/flirtual",
    private: false,
    owner: {
      name: "flirtual",
      email: "hello@flirtual.com",
      login: "flirtual",
      id: 80071112,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjgwMDcxMTEy",
      avatar_url: "https://avatars.githubusercontent.com/u/80071112?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/flirtual",
      html_url: "https://github.com/flirtual",
      followers_url: "https://api.github.com/users/flirtual/followers",
      following_url: "https://api.github.com/users/flirtual/following{/other_user}",
      gists_url: "https://api.github.com/users/flirtual/gists{/gist_id}",
      starred_url: "https://api.github.com/users/flirtual/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/flirtual/subscriptions",
      organizations_url: "https://api.github.com/users/flirtual/orgs",
      repos_url: "https://api.github.com/users/flirtual/repos",
      events_url: "https://api.github.com/users/flirtual/events{/privacy}",
      received_events_url: "https://api.github.com/users/flirtual/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
    },
    html_url: "https://github.com/flirtual/flirtual",
    description: "The first VR dating app",
    fork: false,
    url: "https://api.github.com/repos/flirtual/flirtual",
    forks_url: "https://api.github.com/repos/flirtual/flirtual/forks",
    keys_url: "https://api.github.com/repos/flirtual/flirtual/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/flirtual/flirtual/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/flirtual/flirtual/teams",
    hooks_url: "https://api.github.com/repos/flirtual/flirtual/hooks",
    issue_events_url: "https://api.github.com/repos/flirtual/flirtual/issues/events{/number}",
    events_url: "https://api.github.com/repos/flirtual/flirtual/events",
    assignees_url: "https://api.github.com/repos/flirtual/flirtual/assignees{/user}",
    branches_url: "https://api.github.com/repos/flirtual/flirtual/branches{/branch}",
    tags_url: "https://api.github.com/repos/flirtual/flirtual/tags",
    blobs_url: "https://api.github.com/repos/flirtual/flirtual/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/flirtual/flirtual/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/flirtual/flirtual/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/flirtual/flirtual/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/flirtual/flirtual/statuses/{sha}",
    languages_url: "https://api.github.com/repos/flirtual/flirtual/languages",
    stargazers_url: "https://api.github.com/repos/flirtual/flirtual/stargazers",
    contributors_url: "https://api.github.com/repos/flirtual/flirtual/contributors",
    subscribers_url: "https://api.github.com/repos/flirtual/flirtual/subscribers",
    subscription_url: "https://api.github.com/repos/flirtual/flirtual/subscription",
    commits_url: "https://api.github.com/repos/flirtual/flirtual/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/flirtual/flirtual/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/flirtual/flirtual/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/flirtual/flirtual/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/flirtual/flirtual/contents/{+path}",
    compare_url: "https://api.github.com/repos/flirtual/flirtual/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/flirtual/flirtual/merges",
    archive_url: "https://api.github.com/repos/flirtual/flirtual/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/flirtual/flirtual/downloads",
    issues_url: "https://api.github.com/repos/flirtual/flirtual/issues{/number}",
    pulls_url: "https://api.github.com/repos/flirtual/flirtual/pulls{/number}",
    milestones_url: "https://api.github.com/repos/flirtual/flirtual/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/flirtual/flirtual/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/flirtual/flirtual/labels{/name}",
    releases_url: "https://api.github.com/repos/flirtual/flirtual/releases{/id}",
    deployments_url: "https://api.github.com/repos/flirtual/flirtual/deployments",
    created_at: 1685568044,
    updated_at: "2026-08-17T00:04:46Z",
    pushed_at: 1786929471,
    git_url: "git://github.com/flirtual/flirtual.git",
    ssh_url: "git@github.com:flirtual/flirtual.git",
    clone_url: "https://github.com/flirtual/flirtual.git",
    svn_url: "https://github.com/flirtual/flirtual",
    homepage: "https://flirtual.com",
    size: 23422,
    stargazers_count: 35,
    watchers_count: 35,
    language: "TypeScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 6,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 43,
    license: {
      key: "agpl-3.0",
      name: "GNU Affero General Public License v3.0",
      spdx_id: "AGPL-3.0",
      url: "https://api.github.com/licenses/agpl-3.0",
      node_id: "MDc6TGljZW5zZTE=",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    has_pull_requests: true,
    pull_request_creation_policy: "all",
    topics: ["dating-app", "elixir", "phoenix", "typescript", "vr", "vrchat"],
    visibility: "public",
    forks: 6,
    open_issues: 43,
    watchers: 35,
    default_branch: "main",
    stargazers: 35,
    master_branch: "main",
    organization: "flirtual",
    custom_properties: {
      Meow: "true",
    },
  },
  pusher: {
    name: "flitty-bot[bot]",
    email: null,
  },
  forced: false,
  organization: {
    login: "flirtual",
    id: 80071112,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjgwMDcxMTEy",
    url: "https://api.github.com/orgs/flirtual",
    repos_url: "https://api.github.com/orgs/flirtual/repos",
    events_url: "https://api.github.com/orgs/flirtual/events",
    hooks_url: "https://api.github.com/orgs/flirtual/hooks",
    issues_url: "https://api.github.com/orgs/flirtual/issues",
    members_url: "https://api.github.com/orgs/flirtual/members{/member}",
    public_members_url: "https://api.github.com/orgs/flirtual/public_members{/member}",
    avatar_url: "https://avatars.githubusercontent.com/u/80071112?v=4",
    description: "The first VR dating app.",
  },
  sender: {
    login: "flitty-bot[bot]",
    id: 317127550,
    node_id: "BOT_kgDOEub7fg",
    avatar_url: "https://avatars.githubusercontent.com/in/4598857?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/flitty-bot%5Bbot%5D",
    html_url: "https://github.com/apps/flitty-bot",
    followers_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/followers",
    following_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/following{/other_user}",
    gists_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/gists{/gist_id}",
    starred_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/subscriptions",
    organizations_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/orgs",
    repos_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/repos",
    events_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/events{/privacy}",
    received_events_url: "https://api.github.com/users/flitty-bot%5Bbot%5D/received_events",
    type: "Bot",
    user_view_type: "public",
    site_admin: false,
  },
  created: false,
  deleted: true,
  base_ref: null,
  compare: "https://github.com/flirtual/flirtual/compare/6c7286bd6d3c...000000000000",
  commits: [],
  head_commit: null,
};

const commits = [
  {
    id: "9d2c8e1f4a7b3c6d5e8f9a0b1c2d3e4f5a6b7c8d",
    tree_id: "0000000000000000000000000000000000000000",
    distinct: true,
    message:
      "feat: add retry with backoff to webhook delivery\n\nlonger body that should not appear",
    timestamp: "2026-08-17T12:00:00-07:00",
    url: "https://github.com/flirtual/flirtual/commit/9d2c8e1f4a7b3c6d5e8f9a0b1c2d3e4f5a6b7c8d",
    author: { name: "Aries Clark", email: "aries@example.com", username: "ariesclark" },
    committer: { name: "GitHub", email: "noreply@github.com", username: "web-flow" },
    added: ["src/queue.ts"],
    removed: [],
    modified: ["src/app.ts"],
  },
  {
    id: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    tree_id: "0000000000000000000000000000000000000000",
    distinct: true,
    message:
      "fix(parser): handle `escaped` backticks in commit messages with an intentionally very long subject line to test truncation behavior",
    timestamp: "2026-08-17T12:01:00-07:00",
    url: "https://github.com/flirtual/flirtual/commit/1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    author: { name: "Flitty Bot", email: null, username: "flitty-bot[bot]" },
    committer: { name: "GitHub", email: "noreply@github.com", username: "web-flow" },
    added: [],
    removed: [],
    modified: ["src/options.ts"],
  },
  {
    id: "f0e1d2c3b4a5968778695a4b3c2d1e0f9a8b7c6d",
    tree_id: "0000000000000000000000000000000000000000",
    distinct: true,
    message: "chore: bump dependencies",
    timestamp: "2026-08-17T12:02:00-07:00",
    url: "https://github.com/flirtual/flirtual/commit/f0e1d2c3b4a5968778695a4b3c2d1e0f9a8b7c6d",
    author: { name: "Renovate Bot", email: "bot@renovateapp.com", username: "renovate[bot]" },
    committer: { name: "GitHub", email: "noreply@github.com", username: "web-flow" },
    added: [],
    removed: [],
    modified: ["package.json", "pnpm-lock.yaml"],
  },
];

export const c = {
  ...b,
  ref: "refs/heads/main",
  after: commits[2].id,
  created: false,
  deleted: false,
  forced: false,
  compare: "https://github.com/flirtual/flirtual/compare/6c7286bd6d3c...f0e1d2c3b4a5",
  commits,
  head_commit: commits[2],
} as unknown as GithubEvent;

const secret =
  "1538482839069266001/RGCrOCc49q4mA68vZ-ZqsHJm3LI97IWHTeSmA7htXAUi17Q438Z2wOBPsZsMJYMUiIeK";

if (import.meta.main) {
  const requests: Request[] = [];
  for (const event of [...pushScenarios, ...checkRunScenarios]) {
    const request = await getWebhookRequest(secret, event);
    if (request) requests.push(request);
  }

  const merged = await mergeRequests(requests);
  console.log(`merged ${requests.length} requests into ${merged.length}`);

  for (const request of merged) {
    let response = await fetch(request.clone());

    while (response.status === 429) {
      const { retry_after: retryAfter } = (await response.json()) as { retry_after: number };
      await new Promise((resolve) => setTimeout(resolve, (retryAfter + 0.1) * 1000));
      response = await fetch(request.clone());
    }

    console.log(`${response.status} ${response.ok ? "" : await response.text()}`);
  }
}
